#!/usr/bin/env python3
"""Generate GPT-2 reference token ids for the C++ tokenizer tests.

Uses tiktoken's "gpt2" encoding as the ground truth. The GPT-2 BPE used by
tiktoken produces the same ids as the HuggingFace vocab.json + merges.txt pair
shipped in model/, so this is a valid oracle for encode().

Run:  python3 tools/gen_token_reference.py
Emits: tests/token_test_data.h  (auto-generated; do not edit by hand)
"""

from __future__ import annotations

import os

import tiktoken

# Each case is (short_name, input_string). The set deliberately exercises the
# fiddly parts of GPT-2 BPE: empty input, leading/interior whitespace, digits,
# contractions, punctuation runs, multi-byte UTF-8, control chars, and emoji.
CASES: list[tuple[str, str]] = [
    ("empty",            ""),
    ("single_space",     " "),
    ("hello_world",      "Hello world"),
    ("pangram",          "The quick brown fox jumps over the lazy dog."),
    ("numbers_hyphen",   "GPT-2 was released in 2019."),
    ("double_spaces",    "  leading and  interior  spaces"),
    ("contraction",      "Tokenization isn't always straightforward."),
    ("accents_utf8",     "naïve café résumé"),
    ("control_chars",    "line1\nline2\tcol2\r\n"),
    ("digits_run",       "1234567890 and 007 and 3.14159"),
    ("mixed_case",       "MixedCASE camelCase snake_case SCREAMING"),
    ("emoji",            "rocket 🚀 grin 😀 family 👨‍👩‍👧"),
]

HEADER = "tests/token_test_data.h"


def cpp_bytes(s: str) -> str:
    """Render a Python str as a C++ initializer_list of UTF-8 byte values."""
    return "{" + ", ".join(f"0x{b:02x}" for b in s.encode("utf-8")) + "}"


def readable(s: str) -> str:
    """A safe single-line description for the case comment."""
    return (
        s.replace("\\", "\\\\")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
        .replace("\r", "\\r")
    )


def main() -> None:
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    enc = tiktoken.get_encoding("gpt2")

    lines: list[str] = []
    w = lines.append
    w("// AUTO-GENERATED by tools/gen_token_reference.py -- DO NOT EDIT.")
    w("// Ground-truth GPT-2 token ids from tiktoken.get_encoding(\"gpt2\").")
    w("#pragma once")
    w("")
    w("#include <initializer_list>")
    w("#include <string>")
    w("#include <vector>")
    w("")
    w("struct TokenCase {")
    w("    const char* name;           // short description")
    w("    std::string text;           // input, raw UTF-8 bytes")
    w("    std::vector<int> expected;  // expected GPT-2 token ids")
    w("};")
    w("")
    w("// Build a std::string from explicit bytes so embedded UTF-8 / control")
    w("// characters survive intact and we avoid greedy hex-escape pitfalls.")
    w("inline std::string bytes(std::initializer_list<unsigned char> b) {")
    w("    return std::string(b.begin(), b.end());")
    w("}")
    w("")
    w("inline const std::vector<TokenCase>& token_cases() {")
    w("    static const std::vector<TokenCase> cases = {")

    for name, text in CASES:
        ids = enc.encode(text)  # no special tokens, matches HF gpt2 default
        ids_str = "{" + ", ".join(str(i) for i in ids) + "}"
        w(f'        // "{readable(text)}"')
        w(f'        {{ "{name}", bytes({cpp_bytes(text)}), {ids_str} }},')

    w("    };")
    w("    return cases;")
    w("}")
    w("")

    out_path = os.path.join(repo_root, HEADER)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"wrote {out_path} with {len(CASES)} cases")
    for name, text in CASES:
        print(f"  {name:16s} -> {len(enc.encode(text))} tokens")


if __name__ == "__main__":
    main()
